services:
  - type: web
    name: reward-telegram-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    healthCheckPath: /
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: BROADCAST_DELAY
        value: "0.08"
      - key: CHANNEL_USERNAME
        sync: false
      - key: CHANNEL_CHAT_ID
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: reward-bot-db
          property: connectionString
      - key: WEB_HOST
        value: "0.0.0.0"

databases:
  - name: reward-bot-db
    plan: free
    databaseName: reward_bot
    user: reward_bot
